import type { ID, UnixMs } from '../../../../packages/contracts/src/common.js';
import type { InvocationAuthorizationCommandName, InvocationRiskLevel } from '../../../../packages/contracts/src/invocation-authorization.js';
export interface InvocationAuthorizationFactRecord { readonly id: ID; readonly managementRunId: ID; readonly invocationId: ID; readonly idempotencyKey: string; readonly operationHash: string; readonly inputHash: string; readonly riskLevel: InvocationRiskLevel; readonly deadlineAt: UnixMs | null; readonly plannedEffectIdentitiesJson: string; readonly taskId: ID; readonly frozenRevision: number; readonly frozenAttempt: number; readonly claimLeaseId: ID; readonly state: 'active'|'superseded'|'revoked'; readonly createdAt: UnixMs; readonly supersededAt: UnixMs | null; }
export interface InvocationAuthorizationFactRepository { create(record: InvocationAuthorizationFactRecord): Promise<InvocationAuthorizationFactRecord>; getById(id: ID): Promise<InvocationAuthorizationFactRecord|null>; getByIdempotencyKey(input: { managementRunId: ID; idempotencyKey: string }): Promise<InvocationAuthorizationFactRecord|null>; getByInvocationId(invocationId: ID): Promise<InvocationAuthorizationFactRecord|null>; updateState(input: { id: ID; state: 'superseded'|'revoked'; supersededAt: UnixMs }): Promise<void>; }
export interface InvocationActionApprovalRecord { readonly id: ID; readonly managementRunId: ID; readonly invocationId: ID; readonly authorizationReceiptId: ID; readonly actionRef: string; readonly effectKind: string; readonly dedupKey: string; readonly contentHash: string; readonly approvedRevision: number; readonly approvedAttempt: number; readonly claimLeaseId: ID; readonly approverId: ID; readonly state: 'applied'|'no_op'; readonly createdAt: UnixMs; }
export interface InvocationActionApprovalRepository { create(record: InvocationActionApprovalRecord): Promise<InvocationActionApprovalRecord>; getById(id: ID): Promise<InvocationActionApprovalRecord|null>; getByEffectDedupKey(input: { managementRunId: ID; invocationId: ID; effectKind: string; dedupKey: string }): Promise<InvocationActionApprovalRecord|null>; }
export interface InvocationEffectOutcomeRecord { readonly id: ID; readonly managementRunId: ID; readonly invocationId: ID; readonly effectKind: string; readonly dedupKey: string; readonly contentHash: string; readonly outcome: 'succeeded'|'failed'|'unknown'; readonly externalEffectUnknown: boolean; readonly actionRequired: boolean; readonly resultRef: string|null; readonly errorMessage: string|null; readonly createdAt: UnixMs; }
export interface InvocationEffectOutcomeRepository { create(record: InvocationEffectOutcomeRecord): Promise<InvocationEffectOutcomeRecord>; getByEffectIdentity(input: { managementRunId: ID; invocationId: ID; effectKind: string; dedupKey: string }): Promise<InvocationEffectOutcomeRecord|null>; }
export interface InvocationAuthorizationCommandReceiptRecord { readonly receiptId: ID; readonly teamId: ID; readonly commandName: InvocationAuthorizationCommandName; readonly commandSchemaVersion: number; readonly idempotencyKey: string; readonly commandHash: string; readonly outcome: 'applied'|'no_op'; readonly committedRevisions: ReadonlyArray<{ readonly streamKind: string; readonly streamId: ID; readonly revision: number }>; readonly eventRefs: ReadonlyArray<{ readonly streamKind: string; readonly streamId: ID; readonly sequence: number }>; readonly resultAvailable: boolean; readonly resultJson: string|null; readonly commitTime: UnixMs; readonly createdAt: UnixMs; }
export interface InvocationAuthorizationIdempotencyTombstoneRecord { readonly id: ID; readonly teamId: ID; readonly commandName: InvocationAuthorizationCommandName; readonly idempotencyKey: string; readonly commandHash: string; readonly receiptId: ID; readonly outcome: 'applied'|'no_op'; readonly resultAvailable: boolean; readonly createdAt: UnixMs; }
export interface InvocationAuthorizationReceiptRepository { createReceipt(record: InvocationAuthorizationCommandReceiptRecord): Promise<InvocationAuthorizationCommandReceiptRecord>; getReceiptByIdempotencyKey(idempotencyKey: string): Promise<InvocationAuthorizationCommandReceiptRecord|null>; createTombstone(record: InvocationAuthorizationIdempotencyTombstoneRecord): Promise<InvocationAuthorizationIdempotencyTombstoneRecord>; }
export interface InvocationAuthorizationRepositories { readonly authorizationFacts: InvocationAuthorizationFactRepository; readonly actionApprovals: InvocationActionApprovalRepository; readonly effectOutcomes: InvocationEffectOutcomeRepository; readonly receipts: InvocationAuthorizationReceiptRepository; }
