import type { EffectIdentityV1 } from '@agentbean/contracts';
export function canonicalizeEffectIdentity(e:EffectIdentityV1):string{return JSON.stringify(e)}
export interface ExistingAuthorizationRecord{readonly authorizationId:string;readonly operationHash:string;readonly frozenRevision:number;readonly frozenAttempt:number;readonly frozenClaimLeaseId:string;readonly state:'active'|'superseded'|'revoked'}
export interface EvaluateInvocationAuthorizationInput{readonly managementRunId:string;readonly invocationId:string;readonly requestedOperationHash:string;readonly existing?:ExistingAuthorizationRecord;readonly currentTaskRevision:number;readonly currentTaskAttempt:number;readonly currentClaimLeaseId:string;readonly claimActive:boolean;readonly deadlineAt?:number;readonly now:number}
export type InvocationAuthorizationDecision={readonly kind:'authorized';readonly frozenRevision:number;readonly frozenAttempt:number}|{readonly kind:'replayed';readonly authorizationId:string}|{readonly kind:'conflict';readonly reason:string}|{readonly kind:'rejected';readonly reason:string}
export function evaluateInvocationAuthorization(i:EvaluateInvocationAuthorizationInput):InvocationAuthorizationDecision{if(i.deadlineAt!==undefined&&i.deadlineAt<=i.now)return{kind:'rejected',reason:'deadline_expired'};if(!i.claimActive)return{kind:'rejected',reason:'claim_inactive'};if(!i.existing)return{kind:'authorized',frozenRevision:i.currentTaskRevision,frozenAttempt:i.currentTaskAttempt};if(i.existing.operationHash!==i.requestedOperationHash)return{kind:'conflict',reason:'operation_hash_mismatch'};if(i.existing.frozenRevision!==i.currentTaskRevision)return{kind:'rejected',reason:'revision_changed'};if(i.existing.frozenAttempt!==i.currentTaskAttempt)return{kind:'rejected',reason:'attempt_changed'};if(i.existing.frozenClaimLeaseId!==i.currentClaimLeaseId)return{kind:'rejected',reason:'claim_lease_changed'};if(i.existing.state!=='active')return{kind:'rejected',reason:'authorization_'+i.existing.state};return{kind:'replayed',authorizationId:i.existing.authorizationId}}
export interface ExistingApprovalRecord{readonly approvalId:string;readonly actionRef:string;readonly effectKind:string;readonly dedupKey:string;readonly contentHash:string;readonly state:'applied'|'no_op'}
export interface EvaluateActionApprovalInput{readonly actionRef:string;readonly effectIdentity:EffectIdentityV1;readonly authorizationState:'active'|'superseded'|'revoked';readonly authorizationFrozenRevision:number;readonly currentRevision:number;readonly existingApproval?:ExistingApprovalRecord;readonly requestedEffectCanonical:string}
export type ActionApprovalDecision={readonly kind:'approved'}|{readonly kind:'replayed';readonly approvalId:string}|{readonly kind:'rejected';readonly reason:string}
export function evaluateActionApproval(i:EvaluateActionApprovalInput):ActionApprovalDecision{if(i.authorizationState!=='active')return{kind:'rejected',reason:'authorization_'+i.authorizationState};if(i.authorizationFrozenRevision!==i.currentRevision)return{kind:'rejected',reason:'revision_stale'};if(i.existingApproval?.state==='applied')return{kind:'replayed',approvalId:i.existingApproval.approvalId};return{kind:'approved'}}
export interface ExistingEffectRecord{readonly effectOutcomeId:string;readonly effectKind:string;readonly dedupKey:string;readonly contentHash:string;readonly outcome:'succeeded'|'failed'|'unknown';readonly externalEffectUnknown:boolean}
export interface ResolveEffectIdempotencyInput{readonly effectIdentity:EffectIdentityV1;readonly existing?:ExistingEffectRecord;readonly requestedOutcome:'succeeded'|'failed'|'unknown'}
export type EffectIdempotencyDecision={readonly kind:'create'}|{readonly kind:'replay';readonly effectOutcomeId:string}|{readonly kind:'conflict';readonly reason:string}
export function resolveEffectIdempotency(i:ResolveEffectIdempotencyInput):EffectIdempotencyDecision{if(!i.existing)return{kind:'create'};if(i.existing.contentHash!==i.effectIdentity.contentHash)return{kind:'conflict',reason:'content_hash_mismatch'};if(i.existing.outcome!==i.requestedOutcome)return{kind:'conflict',reason:'outcome_mismatch'};return{kind:'replay',effectOutcomeId:i.existing.effectOutcomeId}}
export interface ClassifyEffectOutcomeInput{readonly outcome:'succeeded'|'failed'|'unknown';readonly isExternalEffectUnknown:boolean}
export type EffectOutcomeClassification={readonly outcome:'succeeded'|'failed';readonly externalEffectUnknown:false;readonly actionRequired:false}|{readonly outcome:'unknown';readonly externalEffectUnknown:true;readonly actionRequired:true}|{readonly outcome:'unknown';readonly externalEffectUnknown:false;readonly actionRequired:false}
export function classifyEffectOutcome(i:ClassifyEffectOutcomeInput):EffectOutcomeClassification{if(i.outcome==='succeeded')return{outcome:'succeeded',externalEffectUnknown:false,actionRequired:false};if(i.outcome==='failed')return{outcome:'failed',externalEffectUnknown:false,actionRequired:false};if(i.isExternalEffectUnknown)return{outcome:'unknown',externalEffectUnknown:true,actionRequired:true};return{outcome:'unknown',externalEffectUnknown:false,actionRequired:false}}
