import type { SqliteDatabase } from './repositories.js';
import type { TaskLifecycleCommandName, TaskLifecycleReceiptOutcome } from '../../../../../packages/contracts/src/index.js';
import type { TaskLifecycleCommandReceiptRecord, TaskLifecycleCommandReceiptRepository, TaskLifecycleIdempotencyTombstoneRecord, TaskLifecycleRepositories } from '../../application/task-lifecycle-repositories.js';
interface RR{receipt_id:string;team_id:string;command_name:TaskLifecycleCommandName;command_schema_version:number;idempotency_key:string;command_hash:string;outcome:TaskLifecycleReceiptOutcome;committed_revisions_json:string;event_refs_json:string;result_available:number;result_json:string|null;commit_time:number;created_at:number;}
interface TR{id:string;team_id:string;command_name:TaskLifecycleCommandName;idempotency_key:string;command_hash:string;receipt_id:string;outcome:TaskLifecycleReceiptOutcome;result_available:number;created_at:number;}
function mr(r:RR|undefined):TaskLifecycleCommandReceiptRecord|null{if(!r)return null;return{receiptId:r.receipt_id,teamId:r.team_id,commandName:r.command_name,commandSchemaVersion:r.command_schema_version,idempotencyKey:r.idempotency_key,commandHash:r.command_hash,outcome:r.outcome,committedRevisions:JSON.parse(r.committed_revisions_json),eventRefs:JSON.parse(r.event_refs_json),resultAvailable:r.result_available===1,resultJson:r.result_json,commitTime:r.commit_time,createdAt:r.created_at};}
function mt(r:TR|undefined):TaskLifecycleIdempotencyTombstoneRecord|null{if(!r)return null;return{id:r.id,teamId:r.team_id,commandName:r.command_name,idempotencyKey:r.idempotency_key,commandHash:r.command_hash,receiptId:r.receipt_id,outcome:r.outcome,resultAvailable:r.result_available===1,createdAt:r.created_at};}
export function createSqliteTaskLifecycleCommandReceiptRepository(teamDb:SqliteDatabase):TaskLifecycleCommandReceiptRepository{const C='receipt_id,team_id,command_name,command_schema_version,idempotency_key,command_hash,outcome,committed_revisions_json,event_refs_json,result_available,result_json,commit_time,created_at';return{async createReceipt(i){teamDb.prepare('INSERT INTO task_lifecycle_command_receipts(receipt_id,team_id,command_name,command_schema_version,idempotency_key,command_hash,outcome,committed_revisions_json,event_refs_json,result_available,result_json,commit_time,created_at)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(i.receiptId,i.teamId,i.commandName,i.commandSchemaVersion,i.idempotencyKey,i.commandHash,i.outcome,JSON.stringify(i.committedRevisions),JSON.stringify(i.eventRefs),i.resultAvailable?1:0,i.resultJson,i.commitTime,i.createdAt);return i;},async getReceiptByIdempotencyKey(k){return mr(teamDb.prepare(`SELECT ${C} FROM task_lifecycle_command_receipts WHERE idempotency_key=?`).get(k)as RR|undefined);},async getReceiptById(id){return mr(teamDb.prepare(`SELECT ${C} FROM task_lifecycle_command_receipts WHERE receipt_id=?`).get(id)as RR|undefined);},async createTombstone(i){teamDb.prepare('INSERT INTO task_lifecycle_idempotency_tombstones(id,team_id,command_name,idempotency_key,command_hash,receipt_id,outcome,result_available,created_at)VALUES(?,?,?,?,?,?,?,?,?)').run(i.id,i.teamId,i.commandName,i.idempotencyKey,i.commandHash,i.receiptId,i.outcome,i.resultAvailable?1:0,i.createdAt);return i;},async getTombstoneByIdempotencyKey(k){return mt(teamDb.prepare('SELECT id,team_id,command_name,idempotency_key,command_hash,receipt_id,outcome,result_available,created_at FROM task_lifecycle_idempotency_tombstones WHERE idempotency_key=?').get(k)as TR|undefined);},};}
export function createSqliteTaskLifecycleRepositories(teamDb:SqliteDatabase):TaskLifecycleRepositories{return{receipts:createSqliteTaskLifecycleCommandReceiptRepository(teamDb)};}
