import type { InvocationActionApprovalRecord,InvocationActionApprovalRepository,InvocationAuthorizationCommandReceiptRecord,InvocationAuthorizationFactRecord,InvocationAuthorizationFactRepository,InvocationAuthorizationIdempotencyTombstoneRecord,InvocationAuthorizationReceiptRepository,InvocationAuthorizationRepositories,InvocationEffectOutcomeRecord,InvocationEffectOutcomeRepository } from '../../application/invocation-authorization-repositories.js';
export interface InvocationAuthorizationMemoryState { authorizationFacts: Map<string,InvocationAuthorizationFactRecord>; actionApprovals: Map<string,InvocationActionApprovalRecord>; effectOutcomes: Map<string,InvocationEffectOutcomeRecord>; receipts: Map<string,InvocationAuthorizationCommandReceiptRecord>; idempotencyKeyIndex: Map<string,string>; effectDedupIndex: Map<string,string>; tombstones: Map<string,InvocationAuthorizationIdempotencyTombstoneRecord> }
export function createInvocationAuthorizationMemoryState(): InvocationAuthorizationMemoryState { return { authorizationFacts:new Map(), actionApprovals:new Map(), effectOutcomes:new Map(), receipts:new Map(), idempotencyKeyIndex:new Map(), effectDedupIndex:new Map(), tombstones:new Map() } }
export function cloneInvocationAuthorizationMemoryState(s:InvocationAuthorizationMemoryState): InvocationAuthorizationMemoryState { return { authorizationFacts:new Map(s.authorizationFacts), actionApprovals:new Map(s.actionApprovals), effectOutcomes:new Map(s.effectOutcomes), receipts:new Map(s.receipts), idempotencyKeyIndex:new Map(s.idempotencyKeyIndex), effectDedupIndex:new Map(s.effectDedupIndex), tombstones:new Map(s.tombstones) } }
export function restoreInvocationAuthorizationMemoryState(t:InvocationAuthorizationMemoryState,s:InvocationAuthorizationMemoryState): void { t.authorizationFacts=new Map(s.authorizationFacts); t.actionApprovals=new Map(s.actionApprovals); t.effectOutcomes=new Map(s.effectOutcomes); t.receipts=new Map(s.receipts); t.idempotencyKeyIndex=new Map(s.idempotencyKeyIndex); t.effectDedupIndex=new Map(s.effectDedupIndex); t.tombstones=new Map(s.tombstones) }
export function createInMemoryInvocationAuthorizationRepositories(state:InvocationAuthorizationMemoryState=createInvocationAuthorizationMemoryState()): InvocationAuthorizationRepositories {
  const F:InvocationAuthorizationFactRepository={async create(r){state.authorizationFacts.set(r.id,r);return r},async getById(id){return state.authorizationFacts.get(id)??null},async getByIdempotencyKey({managementRunId,idempotencyKey}){for(const f of state.authorizationFacts.values())if(f.managementRunId===managementRunId&&f.idempotencyKey===idempotencyKey)return f;return null},async getByInvocationId(inv){for(const f of state.authorizationFacts.values())if(f.invocationId===inv&&f.state==='active')return f;return null},async updateState({id,state:ns,supersededAt}){const e=state.authorizationFacts.get(id);if(e)state.authorizationFacts.set(id,{...e,state:ns,supersededAt})}};
  const A:InvocationActionApprovalRepository={async create(r){state.actionApprovals.set(r.id,r);return r},async getById(id){return state.actionApprovals.get(id)??null},async getByEffectDedupKey({managementRunId,invocationId,effectKind,dedupKey}){const k=`${managementRunId}:${invocationId}:${effectKind}:${dedupKey}`;const aid=state.effectDedupIndex.get(k);return aid?(state.actionApprovals.get(aid)??null):null}};
  const O:InvocationEffectOutcomeRepository={async create(r){state.effectOutcomes.set(r.id,r);state.effectDedupIndex.set(`${r.managementRunId}:${r.invocationId}:${r.effectKind}:${r.dedupKey}`,r.id);return r},async getByEffectIdentity({managementRunId,invocationId,effectKind,dedupKey}){const k=`${managementRunId}:${invocationId}:${effectKind}:${dedupKey}`;const oid=state.effectDedupIndex.get(k);return oid?(state.effectOutcomes.get(oid)??null):null}};
  const R:InvocationAuthorizationReceiptRepository={async createReceipt(r){state.receipts.set(r.receiptId,r);state.idempotencyKeyIndex.set(r.idempotencyKey,r.receiptId);return r},async getReceiptByIdempotencyKey(key){const rid=state.idempotencyKeyIndex.get(key);return rid?(state.receipts.get(rid)??null):null},async createTombstone(r){state.tombstones.set(r.id,r);return r}};
  return { authorizationFacts:F, actionApprovals:A, effectOutcomes:O, receipts:R };
}
